services:
  frontend:
    build:
      context: frontend
    ports:
      - 8080:8080
    develop:
      watch:
        - action: sync
          path: frontend
          target: /app
          ignore:
            - node_modules/
        - action: sync
          path: frontend/public
          target: /app/public
        - action: rebuild
          path: frontend/package.json

  backend:
    build:
      context: backend
    ports:
      - 5050:5050
    develop:
      watch:
        - action: sync
          path: backend
          target: /app
          ignore:
            - __pycache__/
            - .venv/
        - action: rebuild
          path: backend/requirements.txt

  mysql:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=twiKexU_5JXL5tM
      - MYSQL_USER=spencer
      - MYSQL_DATABASE=streaks
      - MYSQL_PASSWORD=twiKexU_5JXL5tM
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db/cnf:/etc/mysql/conf.d
    ports:
      - 3306:3306
      - 33060:33060

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8090:80
    environment:
      - PMA_HOST=mysql

volumes:
  mysql-data: