http {
	server {
		listen				443 ssl;
		ssl_certificate		www.spencerlogin.com.pem;
		ssl_certificate_key	www.spencerlogin.com.key;
		server_name         spencerlogin.com www.spencerlogin.com;

		location /api/ {
			root /app;
			proxy_pass http://backend:5050;
		}

		location / {
			root /app;
			proxy_pass http://frontend:8080;
		}
	}
}

events {}
